services:
    nginx:
        build:
            context: docker/nginx
        ports:
            -   "73:73"
        volumes:
            -   ./:/app

    php-fpm:
        build:
            context: docker/php-fpm
        volumes:
            - ./:/app
